version: '3.7'

services:
  db:
    image: mariadb:10.8.3
    restart: always
    environment:
      MYSQL_DATABASE: 'macapa'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
